### ISSUE TITLE
The .avif and .webp lines are added in the *css style file on one line with multiple spaces.

### ISSUE THREAD

**Issue by Li-Deheng** [dx1ded/gulp-avif-css#1]
`Look at this 👀`

<img width="1112" alt="27204948" src="https://user-images.githubusercontent.com/48417413/180321448-f9a40d53-5f7d-423f-a24e-f5ebf76c6bf1.png">

I wish it looked neater like this

<img width="1112" alt="23020556" src="https://user-images.githubusercontent.com/48417413/180322123-195ba680-2cbf-4e78-913a-455a17909d2e.png">

**Comment by Li-Deheng** [comment]
Also, please add "webp" (`gulp-avif-webp-css`) to the package name to make it immediately clear that this package also adds the .webp format to the style.css.

**Comment by vovados1** [comment]
Thank you for your issue, @Li-Deheng! I'll try to fix it tomorrow

**Comment by vovados1** [comment]
I tried to fix the bug with a view, but unfortunately i have written a code that doesn't allow to fix it without an addition action that requires an addition lib. So everything I'll do is just to change the name of the package.

**Comment by Li-Deheng** [comment]
It seems to me that somewhere in the code, instead of wrapping to a new line `\n`, several tabs `\t` are used.
Can you show in the `*.js` file where exactly is the function that is responsible for inserting the code into the `*.css`?
